zuul:
  routes:
    images:
      path: /api/images/**
      url: http://localhost:8081/images
    prompts:
      path: /api/prompts/** # any requests made to gateway/api/prompts
      url: http://localhost:8081/prompts
